import Image from "next/image";

export default function Home() {
  return (
    <main>

    </main>
  );
}


export const metadata = {
  title: "washington portfolio website",
  description: "Generated by create Next app",
}