export default function Home() {
  return (
    <main>
        This is the main home page
    </main>
  );
}


export const metadata = {
  title: "washington portfolio website",
  description: "Generated by create Next app",
}